var sended=["APA91bGGpdCZEwDW1ugorh3ze9yYtruZF0dRiNaOTZk4UmwrcI1cLQ3TGiVY0yzHGufiIbYvhO1YwL_llNzEe-Cxt470fbNBxYQbrhTZzRh9NSqYJrLTpODIfDdXin8NYyfpzJWO7h45tBB_viLrVUUDvuNnIHeiPw"]

module.exports = sended